Beatmapsets Fixes + small profile fix
nekoraw/guweb pull request #7
Opened 2022-11-19 22:39 UTC by luis10barbo

2022-11-20 00:21 UTC, nekoraw approved these changes
se funcionar ta ótimo

não vou dar merge por agora pra caso vc queira mudar algo dps relacionado a isso

2022-11-20 05:58 UTC, luis10barbo commented
Sim, tem alguns códigos que eu queria mudar, tão estranhos/ineficientes

2022-11-21 14:25 UTC, luis10barbo commented
![image](https://user-images.githubusercontent.com/89195562/203052270-e346e2ce-1398-4bee-9563-a35ef85a4cf7.png)
![image](https://user-images.githubusercontent.com/89195562/203052630-d374f9bb-6972-4df8-941f-466b0b476be4.png)

2022-11-21 15:57 UTC, nekoraw requested changes
eah, na próxima faz em pr's separados cada feature (até esqueci qual feature era pra esse pr ser)

2022-11-21 15:57 UTC, nekoraw commented on templates/beatmapset.html
> +                <div class="best-score-misc-grid">
also, algo que eu esqueci de apontar é que modos diferentes tem parâmetros diferentes (ctb não tem od por exemplo)

2022-11-21 15:59 UTC, nekoraw requested changes
eah na próxima coloca as features em pr separado

2022-11-21 16:11 UTC, luis10barbo commented
> cara internet ficou biruta e foi 4x

KKKKKKKKKKKKKKKKKK

2022-11-21 16:12 UTC, luis10barbo commented on templates/beatmapset.html
> +                <% modsStr(score.mods) %>
é uma boa, só q se n tiver os mods tudo prontinho la pra eu colocar, n vo fazer nesse PR

2023-06-09 15:46 UTC, nekoraw commented
@luis10barbo da uma arrumada ae, ja arrumei o sistema de keys e ta funcionando
atualiza seu branch antes q fiz varias mudancas

2023-06-09 16:51 UTC, luis10barbo commented
Eu to livre agr, dai eu faço isso sim

2023-06-11 09:33 UTC, nekoraw approved these changes
vou confiar q tá tudo ok pq o diff de dois arquivos tão difíceis de ler por causa da mudança na formatação

2023-06-11 14:41 UTC, merged